[ 2025-03-23 00:52:44,973 ] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-03-23 00:52:44,977 ] 107 dagshub - INFO - Accessing as mustafa90-D
[ 2025-03-23 00:52:45,297 ] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/repos/mustafa90-D/netwrok_mlops "HTTP/1.1 200 OK"
[ 2025-03-23 00:52:45,527 ] 1025 httpx - INFO - HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"
[ 2025-03-23 00:52:45,529 ] 107 dagshub - INFO - Initialized MLflow to track repo "mustafa90-D/netwrok_mlops"
[ 2025-03-23 00:52:45,530 ] 107 dagshub - INFO - Repository mustafa90-D/netwrok_mlops initialized!
[ 2025-03-23 00:52:45,534 ] 21 root - INFO - Initiating data ingestion
[ 2025-03-23 00:53:05,924 ] 73 root - INFO - Performed train test split on the dataframe
[ 2025-03-23 00:53:05,924 ] 75 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[ 2025-03-23 00:53:05,924 ] 83 root - INFO - Exporting train and test file path.
[ 2025-03-23 00:53:06,121 ] 92 root - INFO - Exported train and test file path.
[ 2025-03-23 00:53:06,123 ] 23 root - INFO - Data ingestion completed
[ 2025-03-23 00:53:06,129 ] 32 root - INFO - Initiating data validation
[ 2025-03-23 00:53:06,223 ] 32 root - INFO - Required number of columns:2
[ 2025-03-23 00:53:06,223 ] 33 root - INFO - Data frame has columns:31
[ 2025-03-23 00:53:06,223 ] 32 root - INFO - Required number of columns:2
[ 2025-03-23 00:53:06,223 ] 33 root - INFO - Data frame has columns:31
[ 2025-03-23 00:53:06,605 ] 34 root - INFO - Data validation completed
[ 2025-03-23 00:53:06,606 ] 38 root - INFO - Starting data transformation
[ 2025-03-23 00:53:06,606 ] 63 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[ 2025-03-23 00:53:06,606 ] 65 root - INFO - Starting data transformation
[ 2025-03-23 00:53:06,692 ] 48 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[ 2025-03-23 00:53:06,693 ] 53 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[ 2025-03-23 00:53:06,716 ] 46 root - INFO - Entered the save_object method of MainUtils class
[ 2025-03-23 00:53:06,723 ] 50 root - INFO - Exited the save_object method of MainUtils class
[ 2025-03-23 00:53:06,723 ] 46 root - INFO - Entered the save_object method of MainUtils class
[ 2025-03-23 00:53:06,730 ] 50 root - INFO - Exited the save_object method of MainUtils class
[ 2025-03-23 00:53:06,735 ] 44 root - INFO - Data transformation completed
[ 2025-03-23 00:53:06,735 ] 46 root - INFO - Starting model training
[ 2025-03-23 01:06:08,594 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=6, connect=7, read=6, redirect=7, status=7)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:06:33,633 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=5, connect=6, read=6, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589B57F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:06:41,641 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=4, connect=5, read=6, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026555488310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:06:57,642 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=3, connect=4, read=6, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026556692910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:07:34,570 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=2, connect=3, read=6, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265555B92E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:08:38,585 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=1, connect=2, read=6, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265555B9310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:10:38,596 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=0, connect=1, read=6, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589B28E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow-artifacts/artifacts/42b9ad468948401e87f42bf4562d6c4b/186c90d1987e40ecbea07848723e7ddb/artifacts/model/model.pkl
[ 2025-03-23 01:10:38,612 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589B5AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
[ 2025-03-23 01:10:42,616 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589B5D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
[ 2025-03-23 01:10:50,628 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589B5FA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
[ 2025-03-23 01:11:06,631 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589F50D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
[ 2025-03-23 01:11:38,646 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589F53A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
[ 2025-03-23 01:12:42,653 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589F5430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
[ 2025-03-23 01:14:42,659 ] 812 urllib3.connectionpool - WARNING - Retrying (JitteredRetry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000265589F52B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /mustafa90-D/netwrok_mlops.mlflow/api/2.0/mlflow/runs/get?run_uuid=186c90d1987e40ecbea07848723e7ddb&run_id=186c90d1987e40ecbea07848723e7ddb
